### ISSUE TITLE
Blank screen with Firefox

### ISSUE THREAD

**Issue by bristow** [benjamintd/benmaps.fr#69]
I don't understand, Benmaps returns a blank screen with Firefox 68.0.1.

No problem with Chromium but i don't use it !

Thanks for BenMaps !

**Comment by claudiush** [comment]
Loads and works perfectly fine here with Firefox 69.0b11
![image](https://user-images.githubusercontent.com/428616/62705000-eceebc80-b9ec-11e9-88e4-3631db5688f7.png)
Did you try in an incognito window without any extensions/addons?

**Comment by bristow** [comment]
Same thing (blank screen) in incognito mode.

My addons : 
- ublock origin : same thing
- fb container : no problem with it
and after, this is not for trackers...

In Firefox, i have a standard settings on privacy : 
![Sélection_159](https://user-images.githubusercontent.com/1156507/62706693-58865900-b9f0-11e9-88a1-e12251e2ebdd.png)

weird...

**Comment by bristow** [comment]
Hum, i have the same thing with Qwant Maps : https://www.qwant.com/maps/

I'm looking for the problem !

**Comment by bristow** [comment]
I found the bug ! It was on Firefox 68.0.1, i think it will fixed in 68.0.2 : https://bugzilla.mozilla.org/show_bug.cgi?id=1565134

> Unhandled promise rejection Error: "Failed to initialize WebGL."

We can force webgl in about:config

**Comment by baarkerlounger** [comment]
Still getting this in Firefox 77.0.1:

```
Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
```

While in Safari it works fine.
